### PR TITLE
Discriminator fix

### PR DESCRIPTION
**Pull request by VictorGaiva**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #24 #43 #658 

## What is the new behavior?
The value for a Discriminator can now be specified.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by VictorGaiva** [comment]
Added a test case for the issues mentioned above

**Comment by VictorGaiva** [comment]
This PR has a test that is intended to fail, replicating the bug.

**Comment by kodermax** [comment]
I really need this PR

**Comment by vtereshyn** [comment]
do you have plans to merge this PR?

**Comment by VictorGaiva** [comment]
This PR contains a failing test to showcase the specific issue. The core dev team should be able to help to find a solution

**Comment by maximivanov** [comment]
@VictorGaiva Any update on this? Can you suggest a workaround till this is merged? Currently I don't see any way to set the discriminator field value and it cannot be overridden once a document is instantiated.

**Comment by VictorGaiva** [comment]
> @VictorGaiva Any update on this? Can you suggest a workaround till this is merged? Currently I don't see any way to set the discriminator field value and it cannot be overridden once a document is instantiated.

There might be some compatibility issues with this PR. We really need a feedback from someone with more knowledge of this codebase before any progress is made. 

Some maintainer should have had already given some comment on it.

**Comment by maximivanov** [comment]
@kamilmysliwiec all of the 3 linked issues are closed: #24 #43 #658

Yet the feature discussed in all of them (possibility to customize discriminator field value) is still not implemented. This PR addresses it. When possible, can we have some attention here please? 🙏

**Pull request closed without merging**
