### PR TITLE
fix(typings): Make createForClass return unkown instead of any

### PR DESCRIPTION
**Pull request by warreee**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently the createForClass method returns any.

Issue Number: N/A

## What is the new behavior?
The createForClass method returns unkown which is more typesafe.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Maybe instead of explicitly passing `<unknown>` type argument, we could add a type arg to the `createForClass` method with a fallback to `any` if not provided? `createForClass<T = any>`

**Comment by warreee** [comment]
Indeed that would be better!
I updated the PR however with a default to `unknown`: `createForClass<T = unknown>`.
Do you see a reason here to prefer `any` over `unknown`?

**Comment by kamilmysliwiec** [comment]
@warreee I would love to avoid introducing breaking changes. Although `unknown` type provides more type safety, it may introduce breaking changes in the existing applications.

**Comment by warreee** [comment]
@kamilmysliwiec I see, I changed it.

**Comment by kamilmysliwiec** [comment]
Thank you @warreee!

**Pull request merged**
